const db = require("../models");
const { Op } = require("sequelize");
const DropPool = db.DropPool;
const InventoryItem = db.InventoryItem;
const Inventory = db.Inventory;
const User = db.User;

// NOTE: item hash is generated by the database via a trigger on insert
// (e.g. SHA2(CONCAT(item_id, ':', unix_timestamp, ':', random))).
// The application must NOT generate or set `itemHash` here. Instead we
// insert the row and then reload it so the trigger-populated `item_hash`
// becomes available on the returned instance.

/**
 * Simulates an item drop based on the drop rate.
 * @param {string} username - The username of the player.
 * @returns {Promise<object>} - The dropped item details or null if no item dropped.
 */
async function simulateDrop(username, forcedItemId = null) {
  try {
    // Fetch all active drop pool entries
    const dropPool = await DropPool.findAll({
      where: { active: true },
    });

    // If a specific itemId was provided, skip selection and use it
    let droppedItemId = null;
    if (forcedItemId) {
      // validate forcedItemId exists in the active drop pool
      const found = dropPool.find(e => String(e.itemId) === String(forcedItemId));
      if (!found) {
        throw new Error('Forced itemId not found in active drop pool');
      }
      droppedItemId = forcedItemId;
    } else {
      // Calculate cumulative drop rates
      const cumulativeRates = [];
      let cumulativeSum = 0;
      dropPool.forEach((entry) => {
        cumulativeSum += parseFloat(entry.dropRate);
        cumulativeRates.push({
          itemId: entry.itemId,
          cumulativeRate: cumulativeSum,
        });
      });

      // Generate a random number between 0 and the total cumulative rate
      const randomRoll = Math.random() * cumulativeSum;

      // Determine which item (if any) is dropped
      const selected = cumulativeRates.find(
        (entry) => randomRoll <= entry.cumulativeRate
      );

      if (!selected) {
        return null; // No item dropped
      }

      droppedItemId = selected.itemId;
    }

    // Verify user exists
    const user = await User.findOne({ where: { username } });
    if (!user) {
      throw new Error("User not found.");
    }

    // Find or create the user's inventory
    let inventory = await Inventory.findOne({
      where: { username },
    });

    if (!inventory) {
      // Create inventory for user if it doesn't exist
      inventory = await Inventory.create({
        username: username
      });
      console.log(`✅ Created new inventory for user: ${username}`);
    }

    // Insert the dropped item row WITHOUT setting itemHash. The DB trigger
    // will compute and populate the `item_hash` column.
    const newItem = await InventoryItem.create({
      inventoryId: inventory.inventoryId,
      itemId: droppedItemId,
      owner: username,
      obtainedAt: new Date()
    });

    // Reload the instance so trigger-populated fields (item_hash) are present
    await newItem.reload();

    console.log(`✅ Item added to inventory with hash (from DB): ${newItem.itemHash}`);

    return newItem;
  } catch (error) {
    console.error("Error simulating drop:", error);
    throw error;
  }
}

module.exports = { simulateDrop };